#ifndef PUBSUB_H
#define PUBSUB_H

#include <stddef.h>
#include <stdint.h>

typedef enum {
	LOOP = 0,
	SCHEDULER_25HZ,
	SCHEDULER_100HZ,
	SCHEDULER_1KHZ,
	SCHEDULER_2KHZ,
	SCHEDULER_4KHZ,
	SENSOR_IMU_GYRO,
	SENSOR_IMU_ACCEL,
	SENSOR_IMU2_GYRO,
	SENSOR_IMU2_ACCEL,
	SENSOR_COMPASS,
	SENSOR_AIR_PRESSURE,
	SENSOR_ENCODER,
	SENSOR_ACCURATE_ENCODER,
	SENSOR_ATTITUDE_VECTOR,
	SENSOR_ATTITUDE_ANGLE,
	SENSOR_LINEAR_ACCEL,
	INTERNAL_MESSAGE,
	EXTERNAL_MESSAGE,
	COMMAND_CALIBRATE_IMU,
	COMMAND_CALIBRATE_IMU2,
	COMMAND_SET_TARGET_ORIENTATION,
	COMMAND_SET_TARGET_POSITION,
	FAULT_DETECTION,
	TOPIC_NULL
} topic_t;

typedef void (*subscriber_callback_t)(uint8_t *data, size_t size);

void publish(topic_t topic, uint8_t *data, size_t size);
void subscribe(topic_t topic, subscriber_callback_t callback);

#endif
